### PR TITLE
Added support for --ignore-empty and --trim-by-grid CLI options and per-import-type layer masking

### PR DESCRIPTION
**Pull request by aaaaaaaaargh**
Hey, great to see you're still working on this awesome plugin! Still using it here as well and I thought it's time to contribute something.

This is just a small change that adds support for the --ignore-empty and --trim-by-grid options provided by the Aseprite CLI.

Hope you can make use of that (I'm sure I do :)

### CODE REVIEW

**Comment by viniciusgerevini** [comment]
Hey, mate. I'm glad you are still using it. Let me do a quick test here. I didn't know about the `--trim-by-grid` option (it's not even included in the online docs). It looks handy.

I used `--ignore-empty` in the past, but I didn't like the result, because it used to mess with the animation, like Aseprite would still include the frame in the json file, but the spritesheet wouldn't contain that frame.

Let me check what's the current behaviour, because if it's still the same I would prefer not include it, as it can be seen as a bug. Having said that, as you've been using this option I guess they may have fixed it.

Thanks for the contribution. :)

**Comment by aaaaaaaaargh** [comment]
Hey, you're welcome! Always glad to contribute, even if it's just small improvements like this.

Well, I used `--ignore-empty` from within the plugin and it worked pretty well. Not sure if that was due to my sprite, maybe I was just lucky, but it seemed to work pretty smoothly. Anyway, if it bugs you in any way, don't hesitate to remove it.

I didn't know about `--trim-by-grid` as well, seems to be a pretty new feature though.

By the way: I'm still wrapping my head around this import stuff. I'm still not happy with how it's implemented because I had this very special case where I needed the generated resources as .png (or any other regular image asset) in order to generate normal maps using a third party software. 

Right now we can't do that because we are exporting everything to .res directly (hence we end up having the actual .png files in the `.import` folder). I think this should be more flexible somehow, although Godot's weird resource update behaviour is making this really hard. But probably that's a problem for another PR ; )

**Comment by viniciusgerevini** [comment]
Yeah, that would actually have to be another import plugin, because import plugins need to have fixed output (i.e. SpriteFrames). It's actually doable, but it's expected one import to generate only one file.

I've tested both changes. `--trim-by-grid` is working very well. `--ignore-empty` does not work properly, but this is due to how the plugin was implemented. I prefer to leave it out for now, but as soon I clean things up we can put it back.

Also, the new trim is only working at the moment when it is split by layers. You need to copy the logic to `_aseprite_export_spritesheet`.

I like what you did with the Trim options. Way cleaner having the list field. Thanks :)

**Comment by viniciusgerevini** [comment]
Heyo! Thanks. I also didn't get time to get back to this, but I was planing to. I have a few considerations.

> split layers is now in a separate section that's similar to the others (named "Sprite Frames per layer")

I feel this makes it more confusing. Splitting in layers does not behave like the other image options. The other options generate extra artifacts, besides the main one. That's not the case with split layers, also the filename pattern is also applied for the non-split import, but it doesn't look like this in the segregated UI.

> for --ignore-empty would it be okay with you to flag this feature with an 'Experimental' label? I have been using it quite a while now and in my case it is doing fine.

I've done a few tests and it breaks quite often. I guess you were lucky your usage does not fit in the breaking scenarios. I'll be fixing the issue that makes it break soon, so we can release this as well.

Your UI reorganisation actually turns this in a breaking change, so I'll have to release a major version for it. What I'm going to do do is to extract your trim-mode, and merge it isolated as a minor, then I merge your other changes and release as another major once I have the fix.

Thanks for putting the effort on this.

**Comment by ecentinela** [comment]
Sorry to revive this topic, but, is there any plan to include the ignore-empty option?

**Pull request closed without merging**
