### PR TITLE
fix window size issue

### PR DESCRIPTION
**Pull request by viniciusgerevini**
Change WindowDialog to PopupPanel to fix window size issue as reported in #15 and #19 .

Unfortunately, when changing to PopupPanel, the window title is lost. However, I don't feel this is a big of a deal.
Before fix: 
nofixaw

Fix:
Screen Shot 2021-04-20 at 8 58 22 pm

### CODE REVIEW

**Comment by viniciusgerevini** [comment]
Not sure if I like this solution. As no one else reported same problem I will wait until a next release comes, to see if it is fixed.

**Comment by conradhappeliv** [comment]
Hi! Just wanted to note that I ran into this same issue (window improperly sized, leaving the `configuration` button unusable, so I can't set my asperite executable path) and it's preventing me from using this plugin :(

**Comment by viniciusgerevini** [comment]
Thanks for letting me know @conradhappeliv . Which operational system do you use? I'll look into this again.
As a workaround for now, you can use TAB and ENTER to navigate the buttons, so you can change the path. I  believe you are also able  to resize the screen. This may help.

**Comment by conradhappeliv** [comment]
That did the trick - thanks for the tip!

I'm on Windows 10. I see the issue on both computers I've tried it on, with the monitors I'm using being 1440p and 4K (laptop, so highly scaled).

**Comment by viniciusgerevini** [comment]
Interesting. Thanks for the extra info. That does make sense. I saw the issue happening in a retina display, with probably higher DPI than my normal monitors. I knew it was a scaling issue, but at least now I have a pattern. Cheers

**Comment by justdaft** [comment]
Hi I have the same problem on my Macbook pro retina screeen.

**Comment by viniciusgerevini** [comment]
Thanks @justdaft . Good to know. I'm fixing this issue on #25  by moving the wizard screen to the dock.
I reopened the old issue #15 until the new version is released in the asset library. Cheers

**Comment by justdaft** [comment]
Thanks, I am also struggling to get the plug in to work, I can't seem to
get the path to aseprite correctly configured, I am on a mac, do you have
any suggestions?

Billy

**Comment by viniciusgerevini** [comment]
Hi Billy. Try `/Applications/Aseprite.app/Contents/MacOS/aseprite`. This seems to be the default PATH on MacOS.
You can test it by running it on the terminal.

**Comment by justdaft** [comment]
Fantastic, that works, and your latest version of the addon works
perfectly, no more dialog box issues.

Many thanks

**Comment by viniciusgerevini** [comment]
Awesome. Thank you

**Pull request closed without merging**
